#!/usr/bin/env bash
set -euo pipefail

FORCE=false
DRY_RUN=false
TODAY="$(date +%F)"

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=true ;;
    --dry-run) DRY_RUN=true ;;
    *)
      echo "Unknown argument: $arg" >&2
      echo "Usage: bash tools/scripts/bootstrap-docs-system.sh [--dry-run] [--force]" >&2
      exit 2
      ;;
  esac
done

log() {
  printf '%s\n' "$*"
}

ensure_dir() {
  local dir="$1"

  if [[ "$DRY_RUN" == "true" ]]; then
    log "mkdir -p $dir"
    return
  fi

  mkdir -p "$dir"
}

write_file() {
  local path="$1"
  local content="$2"

  ensure_dir "$(dirname "$path")"

  if [[ -f "$path" && "$FORCE" != "true" ]]; then
    log "skip existing: $path"
    return
  fi

  if [[ "$DRY_RUN" == "true" ]]; then
    log "write $path"
    return
  fi

  printf '%s\n' "$content" > "$path"
  log "wrote $path"
}

title_from_path() {
  local path="$1"
  local base
  base="$(basename "$path" .md)"
  base="${base%.meta}"
  base="${base//-/ }"
  base="${base//_/ }"
  printf '%s' "$base" | awk '
    {
      for (i=1;i<=NF;i++) {
        $i=toupper(substr($i,1,1)) substr($i,2)
      }
      print
    }
  '
}

document_type_for_path() {
  local path="$1"

  case "$path" in
    docs/planning/*) echo "Planning" ;;
    docs/governance/*) echo "Governance" ;;
    docs/architecture/adr/*) echo "Architecture" ;;
    docs/architecture/diagrams/*.meta.md) echo "Architecture" ;;
    docs/architecture/*) echo "Architecture" ;;
    docs/lifecycle/*) echo "Lifecycle" ;;
    docs/standards/*) echo "Standard" ;;
    docs/platform/*) echo "Platform" ;;
    docs/onboarding/*) echo "Onboarding" ;;
    docs/README.md|docs/index.md) echo "Onboarding" ;;
    *) echo "Planning" ;;
  esac
}

owner_for_type() {
  local type="$1"

  case "$type" in
    Planning) echo "Product Architecture" ;;
    Governance) echo "Governance" ;;
    Architecture) echo "Architecture" ;;
    Lifecycle) echo "Engineering Productivity" ;;
    Standard) echo "Standards" ;;
    Platform) echo "Platform" ;;
    Onboarding) echo "Documentation" ;;
    *) echo "Documentation" ;;
  esac
}

governance_level_for_type() {
  local type="$1"

  case "$type" in
    Governance|Standard) echo "Binding" ;;
    Architecture|Lifecycle|Platform) echo "Required" ;;
    Planning|Onboarding) echo "Informational" ;;
    *) echo "Informational" ;;
  esac
}

required_sections_for_type() {
  local type="$1"

  case "$type" in
    Planning)
      cat <<'EOF'
## Purpose

Define the intent, scope, concepts, constraints, or sequencing for this part of the documentation system.

## Context

This document participates in the governed documentation corpus and must remain aligned with the documentation knowledge graph.

## Problem Statement

TODO: Replace this placeholder with project-specific planning content before marking this document Approved.

## Requirements / Definitions / Maps

TODO: Add the concrete requirements, definitions, or maps governed by this document.

## Constraints

- Documents must use governed metadata.
- Documents must remain linkable from the documentation knowledge graph.
- Documents must not include forbidden citation-rendering artifacts.

## Open Questions

- TODO: Record unresolved questions.

## Upstream

- docs/index.md

## Downstream

- TODO: Add downstream documents.

## Governance Links

- docs/governance/documentation-governance.md

## Glossary Terms

- Documentation System
- Knowledge Graph
- Governance

## Change History

- Initial scaffold generated by bootstrap script.
EOF
      ;;
    Governance)
      cat <<'EOF'
## Purpose

Define authority, rules, enforcement, and exceptions for this documentation governance area.

## Authority

This document is governed by the Documentation Governance authority model.

## Scope

This applies to the governed documentation corpus unless narrowed by a more specific governance rule.

## Rules

- Governed documentation must declare metadata.
- Governed documentation must use canonical directories.
- Governed documentation must preserve traceability through links and ADR references.

## Enforcement

Enforcement is performed through documentation verification, CI rules, and future graph validation.

## Exceptions

Exceptions require explicit documentation and an approved governance decision.

## Versioning & Lifecycle

Approved governance documents must be changed through governed review.

## Upstream

- docs/governance/governance-charter.md

## Downstream

- TODO: Add downstream governed documents.

## Governance Links

- docs/governance/governance-charter.md

## Glossary Terms

- Governance
- Authority
- Enforcement

## Change History

- Initial scaffold generated by bootstrap script.
EOF
      ;;
    Architecture)
      cat <<'EOF'
## Purpose

Define an architectural view, decision, diagram, or validation structure for the documentation system.

## Architectural Context

The documentation system is a governed, typed, graph-aware corpus with validation and drift detection.

## Components / Views

TODO: Replace with concrete architectural components or views.

## Constraints

- Architecture documents must link relevant ADRs.
- Architecture documents must align with governed metadata and directory rules.
- Architecture diagrams must live under docs/architecture/diagrams/.

## Tradeoffs

TODO: Document tradeoffs and rejected alternatives.

## Related ADRs

- ADR 0001 - Documentation System Topology
- ADR 0002 - Governed Document Metadata
- ADR 0003 - Documentation Knowledge Graph
- ADR 0004 - Documentation CI Validation

## Upstream

- docs/planning/architecture-overview.md

## Downstream

- TODO: Add downstream architecture, lifecycle, platform, or standards documents.

## Governance Links

- docs/governance/documentation-governance.md

## Glossary Terms

- Architecture
- ADR
- Knowledge Graph

## Change History

- Initial scaffold generated by bootstrap script.
EOF
      ;;
    Lifecycle)
      cat <<'EOF'
## Purpose

Define how documentation work moves from idea to governed artifact.

## Workflow

1. Propose documentation change.
2. Generate or edit governed artifact.
3. Validate metadata, structure, links, and graph impact.
4. Review according to governance level.
5. Merge only after verification passes.

## Roles & Responsibilities

- Owner: Maintains document accuracy.
- Reviewer: Validates content and links.
- Governance: Resolves binding rule changes.

## Required Artifacts

- Governed Markdown document.
- Valid metadata.
- Upstream/downstream links.
- Governance links.
- ADR links where applicable.

## Approval Gates

- Informational: reviewer approval.
- Required: domain owner approval.
- Binding: governance approval.

## Escalation Paths

Escalate unresolved conflicts to the document owner and governance authority.

## Upstream

- docs/governance/documentation-governance.md

## Downstream

- TODO: Add lifecycle consumers.

## Governance Links

- docs/governance/documentation-governance.md
- docs/governance/ci-policy.md

## Glossary Terms

- Lifecycle
- ChangePlan
- Verification

## Change History

- Initial scaffold generated by bootstrap script.
EOF
      ;;
    Standard)
      cat <<'EOF'
## Purpose

Define binding standards for this documentation or engineering area.

## Standard Rules

- Use governed metadata.
- Use deterministic file paths.
- Use explicit cross-document links.
- Keep approved/binding documents free of unresolved placeholders.

## Examples

TODO: Add compliant examples.

## Anti-Patterns

- Ungoverned Markdown files.
- Broken relative links.
- Missing metadata.
- Undocumented structural drift.

## Enforcement

This standard is enforced by documentation verification, CI, and future graph validation.

## Upstream

- docs/governance/documentation-governance.md

## Downstream

- TODO: Add downstream standards consumers.

## Governance Links

- docs/governance/documentation-governance.md

## Related ADRs

- ADR 0002 - Governed Document Metadata
- ADR 0004 - Documentation CI Validation

## Glossary Terms

- Standard
- Enforcement
- Metadata

## Change History

- Initial scaffold generated by bootstrap script.
EOF
      ;;
    Platform)
      cat <<'EOF'
## Purpose

Define a platform capability that operates, validates, exposes, or observes the documentation system.

## Responsibilities

- Provide deterministic documentation operations.
- Preserve governance boundaries.
- Support validation, graph construction, and drift detection.

## Architecture / Components

TODO: Define platform components and integration points.

## Operational Requirements

- Commands must be repeatable.
- Reports must be machine-readable.
- Failures must be actionable.

## SLAs / SLOs

TODO: Define operational expectations when the platform is implemented.

## Upstream

- docs/architecture/documentation-system-architecture.md

## Downstream

- TODO: Add downstream platform consumers.

## Governance Links

- docs/governance/documentation-governance.md

## Related ADRs

- ADR 0003 - Documentation Knowledge Graph
- ADR 0004 - Documentation CI Validation

## Glossary Terms

- Platform
- CLI
- API
- Observability

## Change History

- Initial scaffold generated by bootstrap script.
EOF
      ;;
    Onboarding)
      cat <<'EOF'
## Purpose

Provide a human-readable entrypoint into the governed documentation system.

## Audience

Engineers, maintainers, reviewers, and agents working inside the repository.

## Overview

The documentation system is a governed, typed, graph-aware corpus designed for validation, traceability, and drift resistance.

## Key Concepts

- Governed metadata
- Document types
- Cross-document links
- ADR lineage
- Documentation knowledge graph
- Validation pipeline

## Navigation Guide

Start with docs/index.md, then read planning, governance, architecture, lifecycle, standards, platform, and onboarding documents in order.

## Related Documents

- docs/planning/documentation-directory-structure.md
- docs/planning/document-metadata-schema.md
- docs/planning/cross-document-link-model.md
- docs/planning/docs-knowledge-graph-schema.md

## Upstream

- docs/index.md

## Downstream

- TODO: Add downstream onboarding documents.

## Governance Links

- docs/governance/documentation-governance.md

## Glossary Terms

- Onboarding
- Documentation System
- Knowledge Graph

## Change History

- Initial scaffold generated by bootstrap script.
EOF
      ;;
  esac
}

write_markdown_doc() {
  local path="$1"
  local title="$2"
  local type="$3"
  local owner="$4"
  local governance_level="$5"
  local status="${6:-Draft}"
  local body

  body="$(required_sections_for_type "$type")"

  write_file "$path" "---
title: \"$title\"
status: \"$status\"
owner: \"$owner\"
lastUpdated: \"$TODAY\"
governanceLevel: \"$governance_level\"
documentType: \"$type\"
upstream: []
downstream: []
governanceLinks:
  - \"docs/governance/documentation-governance.md\"
adrLinks: []
glossaryTerms: []
---

# $title

$body"
}

write_adr() {
  local path="$1"
  local number="$2"
  local title="$3"
  local status="${4:-Draft}"

  write_file "$path" "---
title: \"ADR $number: $title\"
status: \"$status\"
owner: \"Architecture\"
lastUpdated: \"$TODAY\"
governanceLevel: \"Binding\"
documentType: \"Architecture\"
upstream:
  - \"docs/architecture/adr/index.md\"
downstream: []
governanceLinks:
  - \"docs/governance/documentation-governance.md\"
adrLinks: []
glossaryTerms:
  - \"ADR\"
---

# ADR $number: $title

## Context

TODO: Describe the background and forces that require this decision.

## Decision

TODO: State the decision clearly.

## Rationale

TODO: Explain why this decision was made.

## Consequences

TODO: Describe positive, negative, and neutral consequences.

## Implementation Plan

TODO: Define steps required to implement the decision.

## Rollback Plan

TODO: Define how the decision can be superseded or reversed.

## Supersedes

- None

## Superseded By

- None

## References

- docs/planning/documentation-directory-structure.md
- docs/planning/document-metadata-schema.md
- docs/planning/docs-knowledge-graph-schema.md

## Change History

- Initial scaffold generated by bootstrap script."
}

write_diagram() {
  local path="$1"
  local title="$2"

  write_file "$path" "flowchart TD
  A[Input] --> B[$title]
  B --> C[Validation]
  C --> D[Governed Output]"
}

write_diagram_meta() {
  local path="$1"
  local title="$2"
  local related_doc="$3"
  local diagram_file="$4"

  write_markdown_doc "$path" "$title Metadata" "Architecture" "Architecture" "Required" "Draft"
}

main() {
  local dirs=(
    "docs/planning"
    "docs/governance"
    "docs/architecture/adr"
    "docs/architecture/diagrams"
    "docs/lifecycle"
    "docs/standards"
    "docs/platform"
    "docs/onboarding"
    "tools/scripts"
  )

  for dir in "${dirs[@]}"; do
    ensure_dir "$dir"
  done

  local docs=(
    "docs/README.md|Documentation README|Onboarding"
    "docs/index.md|Documentation Index|Onboarding"

    "docs/planning/vision.md|Vision|Planning"
    "docs/planning/scope.md|Scope|Planning"
    "docs/planning/glossary.md|Glossary|Planning"
    "docs/planning/domain-map.md|Domain Map|Planning"
    "docs/planning/nonfunctional-requirements.md|Nonfunctional Requirements|Planning"
    "docs/planning/risks-and-assumptions.md|Risks And Assumptions|Planning"
    "docs/planning/architecture-overview.md|Architecture Overview|Planning"
    "docs/planning/api-overview.md|API Overview|Planning"
    "docs/planning/release-plan.md|Release Plan|Planning"
    "docs/planning/implementation-sequencing.md|Implementation Sequencing|Planning"
    "docs/planning/documentation-directory-structure.md|Documentation Directory Structure|Planning"
    "docs/planning/documentation-system-component-map.md|Documentation System Component Map|Planning"
    "docs/planning/governed-header-block.md|Governed Header Block|Planning"
    "docs/planning/universal-governed-header-block.md|Universal Governed Header Block|Planning"
    "docs/planning/document-metadata-schema.md|Document Metadata Schema|Planning"
    "docs/planning/governed-document-types.md|Governed Document Types|Planning"
    "docs/planning/cross-document-link-model.md|Cross Document Link Model|Planning"
    "docs/planning/upstream-downstream-dependencies.md|Upstream Downstream Dependencies|Planning"
    "docs/planning/governance-links.md|Governance Links|Planning"
    "docs/planning/glossary-directory-structure.md|Glossary Directory Structure|Planning"
    "docs/planning/glossary-term-linking.md|Glossary Term Linking|Planning"
    "docs/planning/glossary-validation-engine.md|Glossary Validation Engine|Planning"
    "docs/planning/docs-knowledge-graph-schema.md|Documentation Knowledge Graph Schema|Planning"
    "docs/planning/directory-structure-validator.md|Directory Structure Validator|Planning"
    "docs/planning/cross-link-graph-validator.md|Cross Link Graph Validator|Planning"
    "docs/planning/cross-link-consistency-checker.md|Cross Link Consistency Checker|Planning"
    "docs/planning/docs-linting-rules.md|Documentation Linting Rules|Planning"
    "docs/planning/docs-ci-rules.md|Documentation CI Rules|Planning"
    "docs/planning/docs-drift-detector.md|Documentation Drift Detector|Planning"
    "docs/planning/docs-self-validation-pipeline.md|Documentation Self Validation Pipeline|Planning"
    "docs/planning/docs-governance-engine.md|Documentation Governance Engine|Planning"
    "docs/planning/docs-cli.md|Documentation CLI|Planning"
    "docs/planning/docs-api.md|Documentation API|Planning"
    "docs/planning/docs-dashboard.md|Documentation Dashboard|Planning"
    "docs/planning/docs-background-daemon.md|Documentation Background Daemon|Planning"
    "docs/planning/docs-agent-specification.md|Docs Agent Specification|Planning"
    "docs/planning/docs-agent-reasoning-engine.md|Docs Agent Reasoning Engine|Planning"
    "docs/planning/docs-agent-planning-engine.md|Docs Agent Planning Engine|Planning"
    "docs/planning/docs-agent-execution-engine.md|Docs Agent Execution Engine|Planning"
    "docs/planning/docs-agent-governance-interpreter.md|Docs Agent Governance Interpreter|Planning"

    "docs/governance/governance-charter.md|Governance Charter|Governance"
    "docs/governance/authority-map.md|Authority Map|Governance"
    "docs/governance/repository-contract.md|Repository Contract|Governance"
    "docs/governance/contribution-model.md|Contribution Model|Governance"
    "docs/governance/versioning-strategy.md|Versioning Strategy|Governance"
    "docs/governance/ci-policy.md|CI Policy|Governance"
    "docs/governance/documentation-governance.md|Documentation Governance|Governance"
    "docs/governance/documentation-ci-rules.md|Documentation CI Rules|Governance"
    "docs/governance/exception-process.md|Exception Process|Governance"

    "docs/architecture/principles.md|Architecture Principles|Architecture"
    "docs/architecture/system-context.md|System Context|Architecture"
    "docs/architecture/container-diagram.md|Container Diagram|Architecture"
    "docs/architecture/component-diagram.md|Component Diagram|Architecture"
    "docs/architecture/runtime-views.md|Runtime Views|Architecture"
    "docs/architecture/data-flow.md|Data Flow|Architecture"
    "docs/architecture/integration-map.md|Integration Map|Architecture"
    "docs/architecture/constraints.md|Architecture Constraints|Architecture"
    "docs/architecture/documentation-system-architecture.md|Documentation System Architecture|Architecture"
    "docs/architecture/documentation-knowledge-graph.md|Documentation Knowledge Graph|Architecture"
    "docs/architecture/documentation-validation-architecture.md|Documentation Validation Architecture|Architecture"
    "docs/architecture/documentation-agent-architecture.md|Documentation Agent Architecture|Architecture"

    "docs/lifecycle/development-lifecycle.md|Development Lifecycle|Lifecycle"
    "docs/lifecycle/branching-strategy.md|Branching Strategy|Lifecycle"
    "docs/lifecycle/release-lifecycle.md|Release Lifecycle|Lifecycle"
    "docs/lifecycle/change-management.md|Change Management|Lifecycle"
    "docs/lifecycle/incident-response.md|Incident Response|Lifecycle"
    "docs/lifecycle/documentation-lifecycle.md|Documentation Lifecycle|Lifecycle"
    "docs/lifecycle/documentation-changeplan-lifecycle.md|Documentation ChangePlan Lifecycle|Lifecycle"

    "docs/standards/coding-standards.md|Coding Standards|Standard"
    "docs/standards/api-standards.md|API Standards|Standard"
    "docs/standards/testing-standards.md|Testing Standards|Standard"
    "docs/standards/documentation-standards.md|Documentation Standards|Standard"
    "docs/standards/markdown-standards.md|Markdown Standards|Standard"
    "docs/standards/metadata-standards.md|Metadata Standards|Standard"
    "docs/standards/graph-schema-standards.md|Graph Schema Standards|Standard"

    "docs/platform/overview.md|Platform Overview|Platform"
    "docs/platform/tooling.md|Tooling|Platform"
    "docs/platform/ci-cd.md|CI CD|Platform"
    "docs/platform/observability.md|Observability|Platform"
    "docs/platform/documentation-cli.md|Documentation CLI Platform|Platform"
    "docs/platform/documentation-api.md|Documentation API Platform|Platform"
    "docs/platform/documentation-dashboard.md|Documentation Dashboard Platform|Platform"
    "docs/platform/documentation-background-daemon.md|Documentation Background Daemon Platform|Platform"

    "docs/onboarding/README.md|Onboarding README|Onboarding"
    "docs/onboarding/system-overview.md|System Overview|Onboarding"
    "docs/onboarding/how-to-navigate-the-repo.md|How To Navigate The Repo|Onboarding"
    "docs/onboarding/glossary-quickref.md|Glossary Quickref|Onboarding"
    "docs/onboarding/documentation-system-guide.md|Documentation System Guide|Onboarding"
  )

  for entry in "${docs[@]}"; do
    IFS='|' read -r path title type <<< "$entry"
    owner="$(owner_for_type "$type")"
    level="$(governance_level_for_type "$type")"
    write_markdown_doc "$path" "$title" "$type" "$owner" "$level" "Draft"
  done

  write_file "docs/architecture/adr/index.md" "---
title: \"ADR Index\"
status: \"Draft\"
owner: \"Architecture\"
lastUpdated: \"$TODAY\"
governanceLevel: \"Binding\"
documentType: \"Architecture\"
upstream: []
downstream: []
governanceLinks:
  - \"docs/governance/documentation-governance.md\"
adrLinks: []
glossaryTerms:
  - \"ADR\"
---

# ADR Index

## Purpose

Provide the authoritative ledger of Architecture Decision Records.

## ADR List

| Number | Title | Status | Superseded By |
| --- | --- | --- | --- |
| 0001 | Documentation System Topology | Draft | — |
| 0002 | Governed Document Metadata | Draft | — |
| 0003 | Documentation Knowledge Graph | Draft | — |
| 0004 | Documentation CI Validation | Draft | — |

## Governance Links

- docs/governance/documentation-governance.md

## Change History

- Initial scaffold generated by bootstrap script."

  write_file "docs/architecture/adr/_template.md" "---
title: \"ADR Template\"
status: \"Draft\"
owner: \"Architecture\"
lastUpdated: \"$TODAY\"
governanceLevel: \"Binding\"
documentType: \"Architecture\"
upstream:
  - \"docs/architecture/adr/index.md\"
downstream: []
governanceLinks:
  - \"docs/governance/documentation-governance.md\"
adrLinks: []
glossaryTerms:
  - \"ADR\"
---

# ADR <Number>: <Title>

## Context

Describe the background and forces.

## Decision

State the decision clearly.

## Rationale

Explain why this decision was made.

## Consequences

Describe positive and negative outcomes.

## Implementation Plan

Steps required to implement.

## Rollback Plan

How to revert or supersede.

## Supersedes

List ADRs replaced.

## Superseded By

List ADRs that replace this one.

## References

Links to planning, architecture, and governance documents."

  write_file "docs/architecture/adr/_supersession.md" "---
title: \"ADR Supersession Template\"
status: \"Draft\"
owner: \"Architecture\"
lastUpdated: \"$TODAY\"
governanceLevel: \"Binding\"
documentType: \"Architecture\"
upstream:
  - \"docs/architecture/adr/index.md\"
downstream: []
governanceLinks:
  - \"docs/governance/documentation-governance.md\"
adrLinks: []
glossaryTerms:
  - \"ADR\"
---

# ADR <Number>: <Title> Supersession

## Supersedes

- ADR <Old Number>: <Old Title>

## Context

Why the previous ADR is no longer valid.

## Decision

The new decision.

## Migration Plan

How to transition.

## Impact

Affected documents and components.

## References

Links to superseded ADR and related docs."

  write_adr "docs/architecture/adr/0001-documentation-system-topology.md" "0001" "Documentation System Topology"
  write_adr "docs/architecture/adr/0002-governed-document-metadata.md" "0002" "Governed Document Metadata"
  write_adr "docs/architecture/adr/0003-documentation-knowledge-graph.md" "0003" "Documentation Knowledge Graph"
  write_adr "docs/architecture/adr/0004-documentation-ci-validation.md" "0004" "Documentation CI Validation"

  write_diagram "docs/architecture/diagrams/system-context.mmd" "System Context"
  write_diagram "docs/architecture/diagrams/documentation-knowledge-graph.mmd" "Documentation Knowledge Graph"
  write_diagram "docs/architecture/diagrams/validation-pipeline.mmd" "Validation Pipeline"
  write_diagram "docs/architecture/diagrams/docs-agent-flow.mmd" "Docs Agent Flow"

  write_markdown_doc "docs/architecture/diagrams/system-context.meta.md" "System Context Diagram Metadata" "Architecture" "Architecture" "Required" "Draft"
  write_markdown_doc "docs/architecture/diagrams/documentation-knowledge-graph.meta.md" "Documentation Knowledge Graph Diagram Metadata" "Architecture" "Architecture" "Required" "Draft"
  write_markdown_doc "docs/architecture/diagrams/validation-pipeline.meta.md" "Validation Pipeline Diagram Metadata" "Architecture" "Architecture" "Required" "Draft"
  write_markdown_doc "docs/architecture/diagrams/docs-agent-flow.meta.md" "Docs Agent Flow Diagram Metadata" "Architecture" "Architecture" "Required" "Draft"

  write_file ".docs-lint.yml" "version: 1
mode: bootstrap
rules:
  metadata:
    required: true
  forbiddenArtifacts:
    - contentReference[oaicite:
  mergeConflictMarkers:
    enabled: true
  graph:
    enabled: false
  drift:
    enabled: false
"

  log ""
  log "Documentation system bootstrap complete."
  log "Next verification command:"
  log "  bun run verify:docs"
}

main
