#!/usr/bin/env python3
from __future__ import annotations

from datetime import date
from pathlib import Path


TODAY = date.today().isoformat()

WORK_PACKET_PATH = Path("docs/work-packets/WP-0006-verify-generated-workspace-contract.md")
WORK_PACKET_INDEX = Path("docs/work-packets/index.md")
CHECK_SCRIPT_PATH = Path("tools/scripts/check-generated-workspace-contract.sh")


WORK_PACKET = f'''---
title: "WP-0006: Verify Generated Workspace Contract"
status: "Draft"
owner: "Engineering Productivity"
lastUpdated: "{TODAY}"
governanceLevel: "Required"
documentType: "WorkPacket"
upstream:
  - "docs/work-packets/index.md"
  - "docs/changeplans/cp-0009-foundry-init-stabilization.md"
  - "docs/work-packets/WP-0005-fix-init-destination-path-handling.md"
downstream:
  - "tools/scripts/check-generated-workspace-contract.sh"
governanceLinks:
  - "docs/governance/documentation-governance.md"
adrLinks: []
glossaryTerms:
  - "Work Packet"
  - "Repository Contract"
  - "Verification"
  - "Scaffolding"
---

# WP-0006: Verify Generated Workspace Contract

## Purpose

Add a verifier for the workspace generated by the `foundry init` MVP path.

## Problem

The init smoke fixture confirms whether a non-interactive init invocation succeeds, but it does not yet verify the generated workspace as a product artifact.

Foundry MVP requires the generated workspace to have a minimum contract.

## Deliverables

This Work Packet delivers:

1. `tools/scripts/check-generated-workspace-contract.sh`
2. A generated workspace contract summary under `.artifacts/foundry/generated-workspace-contract/`
3. Verification that the init smoke workspace exists
4. Verification of required generated files
5. Verification of required generated directories
6. Verification of required package scripts
7. Verification of Foundry provenance/audit anchors when present

## Contract Under Test

The verifier checks the workspace generated at:

~~~text
.artifacts/foundry/init-workspace/workspace
~~~

Required directories:

- `apps`
- `services`
- `packages`
- `docs`
- `tools/scripts`
- `contracts/openapi`
- `generated/clients`
- `config/foundry`
- `templates`

Required files:

- `package.json`
- `bunfig.toml`
- `README.md`
- `.gitignore`
- `tsconfig.base.json`
- `turbo.json`
- `.github/workflows/ci.yml`
- `tools/scripts/foundry.sh`
- `tools/scripts/verify.sh`
- `packages/cli/src/index.ts`
- `config/foundry/generator-manifest.json`
- `.scaffdog/config.js`

Required scripts in generated `package.json`:

- `foundry`
- `verify`

## Verification

Run:

~~~bash
tools/scripts/check-foundry-init-workspace.sh
tools/scripts/check-generated-workspace-contract.sh
cat .artifacts/foundry/generated-workspace-contract/summary.json
~~~

## Acceptance Criteria

This Work Packet is accepted when:

1. Init workspace smoke succeeds.
2. Generated workspace contract verification succeeds.
3. Summary JSON reports `"ok": true`.
4. The generated workspace contains all required MVP contract directories.
5. The generated workspace contains all required MVP contract files.
6. The generated workspace exposes required baseline package scripts.

## Change History

- Created generated workspace contract verification Work Packet.
'''


CHECK_SCRIPT = r'''#!/usr/bin/env bash
set -u

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT" || exit 1

INIT_ARTIFACT_DIR=".artifacts/foundry/init-workspace"
WORKSPACE_DIR="$INIT_ARTIFACT_DIR/workspace"

ARTIFACT_DIR=".artifacts/foundry/generated-workspace-contract"
SUMMARY_JSON="$ARTIFACT_DIR/summary.json"
SUMMARY_TXT="$ARTIFACT_DIR/summary.txt"

mkdir -p "$ARTIFACT_DIR"
: > "$SUMMARY_TXT"

record() {
  printf '%s\n' "$1" | tee -a "$SUMMARY_TXT"
}

record "Generated workspace contract verification"
record "repo root: $ROOT"
record "workspace dir: $WORKSPACE_DIR"

if [ ! -d "$WORKSPACE_DIR" ]; then
  record "workspace missing: $WORKSPACE_DIR"
fi

python3 - <<'PYTHON_SUMMARY'
from __future__ import annotations

import json
from pathlib import Path

workspace = Path(".artifacts/foundry/init-workspace/workspace")
artifact_dir = Path(".artifacts/foundry/generated-workspace-contract")

required_directories = [
    "apps",
    "services",
    "packages",
    "docs",
    "tools/scripts",
    "contracts/openapi",
    "generated/clients",
    "config/foundry",
    "templates",
]

required_files = [
    "package.json",
    "bunfig.toml",
    "README.md",
    ".gitignore",
    "tsconfig.base.json",
    "turbo.json",
    ".github/workflows/ci.yml",
    "tools/scripts/foundry.sh",
    "tools/scripts/verify.sh",
    "packages/cli/src/index.ts",
    "config/foundry/generator-manifest.json",
    ".scaffdog/config.js",
]

required_scripts = [
    "foundry",
    "verify",
]

optional_provenance_files = [
    ".foundry/init/provenance.json",
    ".foundry/init/audit.ndjson",
]

def exists_dir(relative: str) -> bool:
    return (workspace / relative).is_dir()

def exists_file(relative: str) -> bool:
    return (workspace / relative).is_file()

missing_directories = [
    directory for directory in required_directories if not exists_dir(directory)
]

missing_files = [
    file for file in required_files if not exists_file(file)
]

package_json_path = workspace / "package.json"
package_json = None
package_json_error = None
missing_scripts = list(required_scripts)

if package_json_path.is_file():
    try:
        package_json = json.loads(package_json_path.read_text(encoding="utf-8"))
        scripts = package_json.get("scripts", {})
        if isinstance(scripts, dict):
            missing_scripts = [
                script for script in required_scripts if script not in scripts
            ]
    except json.JSONDecodeError as error:
        package_json_error = str(error)

workspace_files = []
if workspace.is_dir():
    workspace_files = sorted(
        str(path.relative_to(workspace))
        for path in workspace.rglob("*")
        if path.is_file()
    )

optional_provenance = {
    file: exists_file(file) for file in optional_provenance_files
}

report = {
    "ok": (
        workspace.is_dir()
        and not missing_directories
        and not missing_files
        and package_json_error is None
        and not missing_scripts
    ),
    "workspace": str(workspace),
    "workspaceExists": workspace.is_dir(),
    "workspaceFileCount": len(workspace_files),
    "missingDirectories": missing_directories,
    "missingFiles": missing_files,
    "packageJsonValid": package_json_error is None and package_json_path.is_file(),
    "packageJsonError": package_json_error,
    "missingScripts": missing_scripts,
    "optionalProvenance": optional_provenance,
    "workspaceFiles": workspace_files[:300],
    "notes": [],
}

if not workspace.is_dir():
    report["notes"].append(
        "Generated workspace is missing. Run tools/scripts/check-foundry-init-workspace.sh first."
    )

if missing_directories:
    report["notes"].append(
        "Generated workspace is missing required MVP directories."
    )

if missing_files:
    report["notes"].append(
        "Generated workspace is missing required MVP files."
    )

if missing_scripts:
    report["notes"].append(
        "Generated package.json is missing required MVP scripts."
    )

if not all(optional_provenance.values()):
    report["notes"].append(
        "Optional provenance/audit anchors are not fully present yet. This should become required in a later init provenance slice."
    )

(artifact_dir / "summary.json").write_text(
    json.dumps(report, indent=2) + "\n",
    encoding="utf-8",
)

print("")
print("Generated workspace contract summary")
print("====================================")
print("ok:", report["ok"])
print("workspace exists:", report["workspaceExists"])
print("workspace file count:", report["workspaceFileCount"])
print("missing directories:", report["missingDirectories"])
print("missing files:", report["missingFiles"])
print("missing scripts:", report["missingScripts"])
print("optional provenance:", report["optionalProvenance"])

for note in report["notes"]:
    print("note:", note)

print("")
print("Wrote:")
print("- .artifacts/foundry/generated-workspace-contract/summary.json")
print("- .artifacts/foundry/generated-workspace-contract/summary.txt")

if not report["ok"]:
    raise SystemExit(1)
PYTHON_SUMMARY
'''


def write(path: Path, content: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

    if executable:
        path.chmod(0o755)

    print(f"wrote {path}")


def update_work_packet_index() -> None:
    if not WORK_PACKET_INDEX.exists():
        print(f"skipped missing {WORK_PACKET_INDEX}")
        return

    row = "| WP-0006 | Verify Generated Workspace Contract | Draft | `docs/work-packets/WP-0006-verify-generated-workspace-contract.md` |"
    content = WORK_PACKET_INDEX.read_text(encoding="utf-8")

    if row in content:
        print(f"{WORK_PACKET_INDEX} already contains WP-0006")
        return

    marker = "| --- | --- | --- | --- |"

    if marker in content:
        content = content.replace(marker, marker + "\n" + row)
    else:
        content += "\n" + row + "\n"

    WORK_PACKET_INDEX.write_text(content, encoding="utf-8")
    print(f"updated {WORK_PACKET_INDEX}")


def main() -> int:
    write(WORK_PACKET_PATH, WORK_PACKET)
    write(CHECK_SCRIPT_PATH, CHECK_SCRIPT, executable=True)
    update_work_packet_index()

    print("")
    print("Next:")
    print("  tools/scripts/check-foundry-init-workspace.sh")
    print("  tools/scripts/check-generated-workspace-contract.sh")
    print("  cat .artifacts/foundry/generated-workspace-contract/summary.json")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
