import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  createInitWorkspaceUpgradePlan,
  listRequiredInitWorkspaceV1Files
} from "./upgrade-planner.js";

interface VerificationIssue {
  readonly code: string;
  readonly message: string;
}

async function main(): Promise<void> {
  const issues = await verifyUpgradeDetection();

  if (issues.length > 0) {
    console.error("verify:init-upgrade-detection: failed");
    console.error("");

    for (const issue of issues) {
      console.error(`- ${issue.code}: ${issue.message}`);
    }

    process.exit(1);
  }

  console.log("verify:init-upgrade-detection: ok");
}

export async function verifyUpgradeDetection(): Promise<
  readonly VerificationIssue[]
> {
  const issues: VerificationIssue[] = [];
  const fixtureRoot = path.resolve(
    ".artifacts/foundry/tests/init-upgrade-detection"
  );

  await rm(fixtureRoot, { recursive: true, force: true });
  await mkdir(fixtureRoot, { recursive: true });

  try {
    issues.push(...(await verifyCurrentWorkspaceDetection(fixtureRoot)));
    issues.push(...(await verifyUpgradeAvailableDetection(fixtureRoot)));
    issues.push(...(await verifyNotFoundryWorkspaceDetection(fixtureRoot)));
    issues.push(...(await verifyInvalidFoundryWorkspaceDetection(fixtureRoot)));
  } finally {
    await rm(fixtureRoot, { recursive: true, force: true });
  }

  return issues;
}

async function verifyCurrentWorkspaceDetection(
  fixtureRoot: string
): Promise<readonly VerificationIssue[]> {
  const issues: VerificationIssue[] = [];
  const workspaceRoot = path.join(fixtureRoot, "current-workspace");

  await createFoundryWorkspaceFixture({
    workspaceRoot,
    workspaceName: "current-workspace",
    omitFiles: []
  });

  const plan = await createInitWorkspaceUpgradePlan(workspaceRoot);

  if (plan.status !== "current") {
    issues.push({
      code: "current-status-mismatch",
      message: `Expected current workspace status to be "current", received "${plan.status}".`
    });
  }

  if (plan.missingFiles.length !== 0) {
    issues.push({
      code: "current-workspace-has-missing-files",
      message: `Expected zero missing files, received ${plan.missingFiles.length}.`
    });
  }

  if (!plan.detected.generatedByFoundryInit) {
    issues.push({
      code: "current-workspace-not-detected-as-foundry-init",
      message: "Expected current workspace to be detected as generated by foundry init."
    });
  }

  return issues;
}

async function verifyUpgradeAvailableDetection(
  fixtureRoot: string
): Promise<readonly VerificationIssue[]> {
  const issues: VerificationIssue[] = [];
  const workspaceRoot = path.join(fixtureRoot, "upgrade-available-workspace");

  await createFoundryWorkspaceFixture({
    workspaceRoot,
    workspaceName: "upgrade-available-workspace",
    omitFiles: ["SECURITY.md", "docs/ai/CURRENT_STATE.md"]
  });

  const plan = await createInitWorkspaceUpgradePlan(workspaceRoot);

  if (plan.status !== "upgrade-available") {
    issues.push({
      code: "upgrade-available-status-mismatch",
      message: `Expected status "upgrade-available", received "${plan.status}".`
    });
  }

  const missingPaths = new Set(plan.missingFiles.map((file) => file.path));

  if (!missingPaths.has("SECURITY.md")) {
    issues.push({
      code: "upgrade-available-missing-security-not-detected",
      message: "Expected missing SECURITY.md to be detected."
    });
  }

  if (!missingPaths.has("docs/ai/CURRENT_STATE.md")) {
    issues.push({
      code: "upgrade-available-missing-current-state-not-detected",
      message: "Expected missing docs/ai/CURRENT_STATE.md to be detected."
    });
  }

  if (plan.actions.length !== plan.missingFiles.length) {
    issues.push({
      code: "upgrade-available-action-count-mismatch",
      message: `Expected one action per missing file. Missing: ${plan.missingFiles.length}; actions: ${plan.actions.length}.`
    });
  }

  return issues;
}

async function verifyNotFoundryWorkspaceDetection(
  fixtureRoot: string
): Promise<readonly VerificationIssue[]> {
  const issues: VerificationIssue[] = [];
  const workspaceRoot = path.join(fixtureRoot, "not-foundry-workspace");

  await mkdir(workspaceRoot, { recursive: true });
  await writeFile(
    path.join(workspaceRoot, "README.md"),
    "# Not Foundry\n",
    "utf8"
  );

  const plan = await createInitWorkspaceUpgradePlan(workspaceRoot);

  if (plan.status !== "not-foundry-workspace") {
    issues.push({
      code: "not-foundry-status-mismatch",
      message: `Expected status "not-foundry-workspace", received "${plan.status}".`
    });
  }

  if (plan.actions.length !== 0) {
    issues.push({
      code: "not-foundry-has-actions",
      message: "Expected non-Foundry workspace to have zero planned actions."
    });
  }

  return issues;
}

async function verifyInvalidFoundryWorkspaceDetection(
  fixtureRoot: string
): Promise<readonly VerificationIssue[]> {
  const issues: VerificationIssue[] = [];
  const workspaceRoot = path.join(fixtureRoot, "invalid-foundry-workspace");

  await mkdir(path.join(workspaceRoot, ".foundry/init"), { recursive: true });
  await writeJsonFile(path.join(workspaceRoot, ".foundry/init/provenance.json"), {
    schemaVersion: 1,
    generatedBy: {
      tool: "foundry",
      command: "some other command"
    },
    workspace: {
      name: "invalid-foundry-workspace"
    }
  });

  const plan = await createInitWorkspaceUpgradePlan(workspaceRoot);

  if (plan.status !== "invalid-foundry-workspace") {
    issues.push({
      code: "invalid-foundry-status-mismatch",
      message: `Expected status "invalid-foundry-workspace", received "${plan.status}".`
    });
  }

  const hasManualReviewAction = plan.actions.some((action) => {
    return action.type === "manual-review";
  });

  if (!hasManualReviewAction) {
    issues.push({
      code: "invalid-foundry-missing-manual-review",
      message: "Expected invalid Foundry workspace to include a manual-review action."
    });
  }

  return issues;
}

async function createFoundryWorkspaceFixture(input: {
  readonly workspaceRoot: string;
  readonly workspaceName: string;
  readonly omitFiles: readonly string[];
}): Promise<void> {
  const omitted = new Set(input.omitFiles);

  for (const requiredFile of listRequiredInitWorkspaceV1Files()) {
    if (omitted.has(requiredFile.path)) {
      continue;
    }

    const absolutePath = path.join(input.workspaceRoot, requiredFile.path);

    if (requiredFile.path === ".foundry/init/provenance.json") {
      await writeJsonFile(absolutePath, {
        schemaVersion: 1,
        generatedBy: {
          tool: "foundry",
          command: "foundry init",
          package: "@foundry/cli"
        },
        workspace: {
          name: input.workspaceName,
          databaseProvider: null,
          installDependencies: false
        },
        generatedFiles: []
      });
      continue;
    }

    if (requiredFile.path === ".foundry/init/audit.ndjson") {
      await writeTextFile(
        absolutePath,
        `${JSON.stringify({
          schemaVersion: 1,
          type: "foundry.init.workspace_created",
          subject: {
            kind: "workspace",
            name: input.workspaceName
          }
        })}\n`
      );
      continue;
    }

    if (requiredFile.path.endsWith(".json")) {
      await writeJsonFile(absolutePath, {});
      continue;
    }

    await writeTextFile(
      absolutePath,
      `# ${requiredFile.path}\n\n${requiredFile.description}\n`
    );
  }
}

async function writeJsonFile(
  filePath: string,
  value: unknown
): Promise<void> {
  await writeTextFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

async function writeTextFile(
  filePath: string,
  contents: string
): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, contents, "utf8");
}

await main();