import { Args, Command, Flags } from "@oclif/core";
import path from "node:path";

import {
  createInitWorkspaceUpgradePlan,
  type InitWorkspaceUpgradeAction,
  type InitWorkspaceUpgradePlan,
  type InitWorkspaceUpgradeWarning
} from "../../init/upgrade-planner.js";

export default class InitUpgrade extends Command {
  static override readonly description =
    "Plan upgrades for a Foundry-generated workspace.";

  static override readonly examples = [
    "<%= config.bin %> <%= command.id %>",
    "<%= config.bin %> <%= command.id %> .",
    "<%= config.bin %> <%= command.id %> myapp",
    "<%= config.bin %> <%= command.id %> myapp --json",
    "<%= config.bin %> <%= command.id %> myapp --check"
  ];

  static override readonly args = {
    workspace: Args.string({
      description:
        "Workspace directory to inspect. Defaults to the current invocation directory.",
      required: false
    })
  };

  static override readonly flags = {
    json: Flags.boolean({
      default: false,
      description: "Print the upgrade plan as JSON."
    }),

    check: Flags.boolean({
      default: false,
      description:
        "Exit with a non-zero status when the workspace is not current."
    })
  };

  async run(): Promise<void> {
    const { args, flags } = await this.parse(InitUpgrade);
    const workspaceRoot = resolveWorkspaceRoot(args.workspace);
    const plan = await createInitWorkspaceUpgradePlan(workspaceRoot);

    if (flags.json) {
      this.log(JSON.stringify(plan, null, 2));
    } else {
      printUpgradePlan(this, plan);
    }

    if (flags.check && plan.status !== "current") {
      this.exit(1);
    }
  }
}

function resolveWorkspaceRoot(workspace: string | undefined): string {
  const invocationCwd = getInvocationCwd();
  const workspaceValue = workspace ?? ".";

  return path.isAbsolute(workspaceValue)
    ? path.resolve(workspaceValue)
    : path.resolve(invocationCwd, workspaceValue);
}

function getInvocationCwd(): string {
  const invocationCwd = process.env.FOUNDRY_INVOCATION_CWD;

  if (typeof invocationCwd === "string" && invocationCwd.trim().length > 0) {
    return path.resolve(invocationCwd);
  }

  return process.cwd();
}

function printUpgradePlan(
  command: Command,
  plan: InitWorkspaceUpgradePlan
): void {
  command.log("");
  command.log("Foundry init upgrade plan");
  command.log("");
  command.log(`Workspace: ${plan.workspaceRoot}`);
  command.log(`Status: ${plan.status}`);
  command.log(`Current version: ${plan.currentVersion ?? "unknown"}`);
  command.log(`Target version: ${plan.targetVersion}`);

  command.log("");
  command.log("Detection:");
  command.log(
    `- Foundry directory: ${formatBoolean(plan.detected.hasFoundryDirectory)}`
  );
  command.log(
    `- Init provenance: ${formatBoolean(plan.detected.hasInitProvenance)}`
  );
  command.log(
    `- Init audit log: ${formatBoolean(plan.detected.hasInitAuditLog)}`
  );
  command.log(
    `- Generator manifest: ${formatBoolean(plan.detected.hasGeneratorManifest)}`
  );
  command.log(
    `- Generated by foundry init: ${formatBoolean(plan.detected.generatedByFoundryInit)}`
  );

  printWarnings(command, plan.warnings);

  command.log("");
  command.log(`Present required files: ${plan.presentFiles.length}`);
  command.log(`Missing required files: ${plan.missingFiles.length}`);

  if (plan.missingFiles.length > 0) {
    command.log("");
    command.log("Missing files:");

    for (const file of plan.missingFiles) {
      command.log(`- ${file.path}`);
      command.log(`  ${file.description}`);
    }
  }

  printActions(command, plan.actions);

  command.log("");
  command.log("Result:");

  switch (plan.status) {
    case "current":
      command.log("- Workspace is current for the known Foundry init baseline.");
      break;

    case "upgrade-available":
      command.log("- Workspace can be upgraded. This command is currently read-only.");
      command.log("- Review the listed actions before using a future mutating upgrade command.");
      break;

    case "not-foundry-workspace":
      command.log("- Workspace does not appear to be generated by foundry init.");
      break;

    case "invalid-foundry-workspace":
      command.log("- Workspace has Foundry metadata but requires manual review.");
      break;

    default:
      assertNever(plan.status);
  }
}

function printWarnings(
  command: Command,
  warnings: readonly InitWorkspaceUpgradeWarning[]
): void {
  if (warnings.length === 0) {
    return;
  }

  command.log("");
  command.log("Warnings:");

  for (const warning of warnings) {
    command.log(`- ${warning.code}`);
    command.log(`  ${warning.message}`);
  }
}

function printActions(
  command: Command,
  actions: readonly InitWorkspaceUpgradeAction[]
): void {
  if (actions.length === 0) {
    return;
  }

  command.log("");
  command.log("Planned actions:");

  for (const action of actions) {
    command.log(`- ${action.type}: ${action.path}`);
    command.log(`  ${action.description}`);
  }
}

function formatBoolean(value: boolean): string {
  return value ? "yes" : "no";
}

function assertNever(value: never): never {
  throw new Error(`Unhandled upgrade plan status: ${String(value)}`);
}